# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# 自动部署
name: auto-deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 安装依赖
    - name: Install dependencies
      run: |
        npm i --unsafe-perm=tr
  
    # 运行构建脚本
    - name: Build Site
      run: |
        # 构建
        npm run build
        

    # 查看 workflow 的文档来获取更多信息
    # @see https://github.com/crazy-max/ghaction-github-pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        # 部署到 gh-pages 分支
        target_branch: gh-pages
        # 部署目录为 VuePress 的默认输出目录
        build_dir: build/
      env:
        # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
